# frozen_string_literal: true
# Команда: bundle install
source "https://rubygems.org"

gem 'sqlite3'
gem "glimmer-dsl-libui", "~> 0.7.4"
gem 'win32api'
gem 'rubocop'
gem 'minitest'
gem 'test-unit'
gem 'rspec'
gem 'server'
group :development, :test do
  gem 'rspec'
end