# frozen_string_literal: true
# Команда: bundle install
source "https://rubygems.org"

gem 'mysql2'
gem "glimmer-dsl-libui", "~> 0.7.4"
gem 'win32api'
gem 'rubocop'
gem 'minitest'
gem 'test-unit'
gem 'rspec'
